
DROP DATABASE IF EXISTS mini_world_db;
CREATE DATABASE mini_world_db;
USE mini_world_db;



-- Location lookup table
CREATE TABLE LOCATION (
    LocationID INT PRIMARY KEY AUTO_INCREMENT,
    City VARCHAR(100) NOT NULL,
    Region VARCHAR(50) NOT NULL,
    UNIQUE (City, Region)
);

-- Pokemon Type lookup table
CREATE TABLE POKEMON_TYPE (
    TypeID INT PRIMARY KEY AUTO_INCREMENT,
    TypeName VARCHAR(20) UNIQUE NOT NULL
);

-- Pokemon Species lookup table (3NF: Species attributes separate from individual Pokemon)
CREATE TABLE POKEMON_SPECIES (
    SpeciesID INT PRIMARY KEY AUTO_INCREMENT,
    SpeciesName VARCHAR(50) UNIQUE NOT NULL,
    PrimaryTypeID INT NOT NULL,
    SecondaryTypeID INT,
    BaseMaxHP INT NOT NULL,
    FOREIGN KEY (PrimaryTypeID) REFERENCES POKEMON_TYPE(TypeID) ON DELETE RESTRICT,
    FOREIGN KEY (SecondaryTypeID) REFERENCES POKEMON_TYPE(TypeID) ON DELETE RESTRICT
);

-- Move lookup table (3NF: Move attributes separate from Pokemon_Move)
CREATE TABLE MOVE (
    MoveID INT PRIMARY KEY AUTO_INCREMENT,
    MoveName VARCHAR(50) UNIQUE NOT NULL,
    MoveTypeID INT NOT NULL,
    MovePower INT,
    FOREIGN KEY (MoveTypeID) REFERENCES POKEMON_TYPE(TypeID) ON DELETE RESTRICT
);

-- Item Type lookup table
CREATE TABLE ITEM_TYPE (
    ItemTypeID INT PRIMARY KEY AUTO_INCREMENT,
    TypeName VARCHAR(50) UNIQUE NOT NULL
);



-- 1. TRAINER
CREATE TABLE TRAINER (
    TrainerID INT PRIMARY KEY AUTO_INCREMENT,
    RegistrationNumber VARCHAR(50) NOT NULL UNIQUE,
    TrainerName VARCHAR(100) NOT NULL,
    HometownLocationID INT,
    RegistrationDate DATE NOT NULL,
    ExperienceLevel ENUM('Novice', 'Intermediate', 'Advanced', 'Expert', 'Master') NOT NULL DEFAULT 'Novice',
    TotalBadges INT NOT NULL DEFAULT 0,
    ContactEmail VARCHAR(100),
    FOREIGN KEY (HometownLocationID) REFERENCES LOCATION(LocationID) ON DELETE SET NULL
);

-- 2. POKEMON
CREATE TABLE POKEMON (
    PokemonID INT PRIMARY KEY AUTO_INCREMENT,
    TrainerID INT NOT NULL,
    SpeciesID INT NOT NULL,
    Nickname VARCHAR(50) NOT NULL,
    Level INT NOT NULL DEFAULT 1,
    ExperiencePoints INT NOT NULL DEFAULT 0,
    CurrentHP INT NOT NULL,
    IsShiny BOOLEAN DEFAULT FALSE,
    CatchDate DATE NOT NULL,
    FriendshipLevel INT NOT NULL DEFAULT 0,
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (SpeciesID) REFERENCES POKEMON_SPECIES(SpeciesID) ON DELETE RESTRICT
);

-- 3. GYM
CREATE TABLE GYM (
    GymID INT PRIMARY KEY AUTO_INCREMENT,
    GymName VARCHAR(100) NOT NULL,
    LocationID INT NOT NULL,
    TypeSpecialtyID INT NOT NULL,
    BadgeName VARCHAR(50) NOT NULL,
    DifficultyLevel INT NOT NULL,
    FOREIGN KEY (LocationID) REFERENCES LOCATION(LocationID) ON DELETE RESTRICT,
    FOREIGN KEY (TypeSpecialtyID) REFERENCES POKEMON_TYPE(TypeID) ON DELETE RESTRICT
);

-- 4. GYM_LEADER
CREATE TABLE GYM_LEADER (
    LeaderID INT PRIMARY KEY AUTO_INCREMENT,
    LeaderName VARCHAR(100) NOT NULL,
    SpecializationTypeID INT NOT NULL,
    YearsActive INT NOT NULL DEFAULT 0,
    SignaturePokemonSpeciesID INT,
    LeaderRank INT,
    FOREIGN KEY (SpecializationTypeID) REFERENCES POKEMON_TYPE(TypeID) ON DELETE RESTRICT,
    FOREIGN KEY (SignaturePokemonSpeciesID) REFERENCES POKEMON_SPECIES(SpeciesID) ON DELETE SET NULL
);

-- 5. TOURNAMENT
CREATE TABLE TOURNAMENT (
    TournamentID INT PRIMARY KEY AUTO_INCREMENT,
    TournamentName VARCHAR(100) NOT NULL,
    LocationID INT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    EntryBadgeRequirement INT NOT NULL DEFAULT 0,
    TournamentStatus ENUM('Upcoming', 'Active', 'Completed', 'Cancelled') NOT NULL DEFAULT 'Upcoming',
    MaxParticipants INT NOT NULL,
    FOREIGN KEY (LocationID) REFERENCES LOCATION(LocationID) ON DELETE RESTRICT
);

-- 6. ITEM
CREATE TABLE ITEM (
    ItemID INT PRIMARY KEY AUTO_INCREMENT,
    ItemName VARCHAR(100) NOT NULL UNIQUE,
    ItemTypeID INT NOT NULL,
    RarityLevel ENUM('Common', 'Uncommon', 'Rare', 'Very Rare', 'Legendary') NOT NULL,
    EffectDescription TEXT,
    FOREIGN KEY (ItemTypeID) REFERENCES ITEM_TYPE(ItemTypeID) ON DELETE RESTRICT
);

-- 3NF: Item pricing separated
CREATE TABLE ITEM_PRICING (
    ItemID INT PRIMARY KEY,
    PurchaseCost DECIMAL(10, 2) NOT NULL,
    SellValue DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID) ON DELETE CASCADE
);


-- 7. BATTLE_RECORD
CREATE TABLE BATTLE_RECORD (
    TrainerID INT,
    BattleID INT,
    BattleDate DATETIME NOT NULL,
    OpponentType VARCHAR(50) NOT NULL,
    BattleOutcome ENUM('Victory', 'Defeat', 'Draw') NOT NULL,
    ExperienceGained INT NOT NULL DEFAULT 0,
    PRIMARY KEY (TrainerID, BattleID),
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE
);

-- 8. POKEMON_MOVE (3NF: References MOVE table)
CREATE TABLE POKEMON_MOVE (
    PokemonID INT,
    MoveSlotNumber INT,
    MoveID INT NOT NULL,
    PRIMARY KEY (PokemonID, MoveSlotNumber),
    FOREIGN KEY (PokemonID) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE,
    FOREIGN KEY (MoveID) REFERENCES MOVE(MoveID) ON DELETE RESTRICT
);



CREATE TABLE LEGENDARY_POKEMON (
    PokemonID INT PRIMARY KEY,
    LegendaryTier ENUM('Minor', 'Major', 'Mythical') NOT NULL,
    CaptureRateModifier DECIMAL(5, 2) NOT NULL,
    SpecialAbility VARCHAR(100),
    FOREIGN KEY (PokemonID) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE
);

CREATE TABLE STARTER_POKEMON (
    PokemonID INT PRIMARY KEY,
    StarterGeneration INT NOT NULL,
    RegionOriginID INT NOT NULL,
    EvolutionStage INT NOT NULL,
    FOREIGN KEY (PokemonID) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE,
    FOREIGN KEY (RegionOriginID) REFERENCES LOCATION(LocationID) ON DELETE RESTRICT
);


-- R1: OWNS
CREATE TABLE OWNS (
    TrainerID INT,
    PokemonID INT,
    AcquisitionDate DATE NOT NULL,
    CatchLocationID INT,
    IsInActiveParty BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (TrainerID, PokemonID),
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (PokemonID) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE,
    FOREIGN KEY (CatchLocationID) REFERENCES LOCATION(LocationID) ON DELETE SET NULL
);

-- R2: CHALLENGES
CREATE TABLE CHALLENGES (
    TrainerID INT,
    GymID INT,
    ChallengeDate DATETIME NOT NULL,
    ChallengeResult ENUM('Victory', 'Defeat', 'In Progress') NOT NULL,
    AttemptsCount INT NOT NULL DEFAULT 1,
    BadgeEarned BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (TrainerID, GymID),
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (GymID) REFERENCES GYM(GymID) ON DELETE CASCADE
);

-- R3: LEADS
CREATE TABLE LEADS (
    LeaderID INT PRIMARY KEY,
    GymID INT NOT NULL UNIQUE,
    AppointmentDate DATE NOT NULL,
    TenureYears INT NOT NULL DEFAULT 0,
    FOREIGN KEY (LeaderID) REFERENCES GYM_LEADER(LeaderID) ON DELETE RESTRICT,
    FOREIGN KEY (GymID) REFERENCES GYM(GymID) ON DELETE RESTRICT
);

-- R4: PARTICIPATES_IN
CREATE TABLE PARTICIPATES_IN (
    TrainerID INT,
    TournamentID INT,
    RegistrationDate DATE NOT NULL,
    PlacementRank INT,
    RoundsWon INT NOT NULL DEFAULT 0,
    IsEliminated BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (TrainerID, TournamentID),
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (TournamentID) REFERENCES TOURNAMENT(TournamentID) ON DELETE CASCADE
);

-- R5: CARRIES
CREATE TABLE CARRIES (
    TrainerID INT,
    ItemID INT,
    QuantityOwned INT NOT NULL DEFAULT 1,
    AcquisitionDate DATE NOT NULL,
    PRIMARY KEY (TrainerID, ItemID),
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID) ON DELETE CASCADE
);

-- R6: BEFRIENDS
CREATE TABLE BEFRIENDS (
    TrainerID1 INT,
    TrainerID2 INT,
    FriendshipDate DATE NOT NULL,
    FriendshipLevel ENUM('Acquaintance', 'Friend', 'Best Friend', 'Rival') NOT NULL DEFAULT 'Friend',
    TradeCount INT NOT NULL DEFAULT 0,
    PRIMARY KEY (TrainerID1, TrainerID2),
    FOREIGN KEY (TrainerID1) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (TrainerID2) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE
);

-- R7: HOLDS
CREATE TABLE HOLDS (
    PokemonID INT PRIMARY KEY,
    ItemID INT NOT NULL,
    EquippedDate DATE NOT NULL,
    BoostPercentage DECIMAL(5, 2),
    FOREIGN KEY (PokemonID) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID) ON DELETE RESTRICT
);

-- R8: EVOLVES_INTO
CREATE TABLE EVOLVES_INTO (
    PreEvolutionID INT PRIMARY KEY,
    PostEvolutionID INT NOT NULL UNIQUE,
    EvolutionTrigger ENUM('Level', 'Item', 'Trade', 'Friendship', 'Stone') NOT NULL,
    RequiredLevel INT,
    RequiredItemID INT,
    FOREIGN KEY (PreEvolutionID) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE,
    FOREIGN KEY (PostEvolutionID) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE,
    FOREIGN KEY (RequiredItemID) REFERENCES ITEM(ItemID) ON DELETE SET NULL
);



-- TERNARY: BATTLE_PARTICIPATION
CREATE TABLE BATTLE_PARTICIPATION (
    ParticipationID INT PRIMARY KEY AUTO_INCREMENT,
    TrainerID INT NOT NULL,
    PokemonID INT NOT NULL,
    GymID INT NOT NULL,
    BattleDate DATETIME NOT NULL,
    BattleResult ENUM('Victory', 'Defeat') NOT NULL,
    TotalTurns INT NOT NULL,
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (PokemonID) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE,
    FOREIGN KEY (GymID) REFERENCES GYM(GymID) ON DELETE CASCADE
);

-- QUATERNARY #1: TRAINING_SESSION
CREATE TABLE TRAINING_SESSION (
    SessionID INT PRIMARY KEY AUTO_INCREMENT,
    TrainerID INT NOT NULL,
    PokemonID INT NOT NULL,
    ItemID INT NOT NULL,
    LocationID INT NOT NULL,
    SessionDate DATETIME NOT NULL,
    DurationMinutes INT NOT NULL,
    SuccessRate DECIMAL(5, 2),
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (PokemonID) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID) ON DELETE CASCADE,
    FOREIGN KEY (LocationID) REFERENCES LOCATION(LocationID) ON DELETE CASCADE
);

-- QUINARY: TOURNAMENT_BATTLE
CREATE TABLE TOURNAMENT_BATTLE (
    BattleID INT PRIMARY KEY AUTO_INCREMENT,
    TournamentID INT NOT NULL,
    TrainerID1 INT NOT NULL,
    PokemonID1 INT NOT NULL,
    TrainerID2 INT NOT NULL,
    PokemonID2 INT NOT NULL,
    BattleDate DATETIME NOT NULL,
    RoundNumber INT NOT NULL,
    WinnerTrainerID INT,
    BattleDurationMinutes INT NOT NULL,
    FOREIGN KEY (TournamentID) REFERENCES TOURNAMENT(TournamentID) ON DELETE CASCADE,
    FOREIGN KEY (TrainerID1) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (PokemonID1) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE,
    FOREIGN KEY (TrainerID2) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (PokemonID2) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE,
    FOREIGN KEY (WinnerTrainerID) REFERENCES TRAINER(TrainerID) ON DELETE SET NULL
);

-- QUATERNARY #2: GYM_TRAINING_PROGRAM
CREATE TABLE GYM_TRAINING_PROGRAM (
    ProgramID INT PRIMARY KEY AUTO_INCREMENT,
    TrainerID INT NOT NULL,
    PokemonID INT NOT NULL,
    GymID INT NOT NULL,
    ItemID INT NOT NULL,
    EnrollmentDate DATE NOT NULL,
    CompletionDate DATE,
    ProgramType ENUM('Type Mastery', 'Speed Training', 'Defense Training', 'Attack Training') NOT NULL,
    ProgressPercentage DECIMAL(5, 2) NOT NULL DEFAULT 0,
    CertificateEarned BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (PokemonID) REFERENCES POKEMON(PokemonID) ON DELETE CASCADE,
    FOREIGN KEY (GymID) REFERENCES GYM(GymID) ON DELETE CASCADE,
    FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID) ON DELETE CASCADE
);



CREATE TABLE TRAINER_BADGE_COLLECTION (
    TrainerID INT,
    BadgeNumber INT,
    BadgeName VARCHAR(50) NOT NULL,
    GymID INT NOT NULL,
    EarnedDate DATE NOT NULL,
    PRIMARY KEY (TrainerID, BadgeNumber),
    FOREIGN KEY (TrainerID) REFERENCES TRAINER(TrainerID) ON DELETE CASCADE,
    FOREIGN KEY (GymID) REFERENCES GYM(GymID) ON DELETE RESTRICT
);

